### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by zipckkk** [wenzhu23333/Differential-Privacy-Based-Federated-Learning#24]
你好，我在运行命令：python main.py --dataset mnist --model cnn --dp_mechanism Gaussian --dp_epsilon 10 --dp_delta 1e-5 --dp_clip 10时报错
D:\Anaconda\envs\gym_gpu\lib\site-packages\torchvision\datasets\mnist.py:65: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")
GradSampleModule(CNNMnist(
  (conv1): Conv2d(1, 10, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(10, 20, kernel_size=(5, 5), stride=(1, 1))
  (conv2_drop): Dropout2d(p=0.5, inplace=False)
  (fc1): Linear(in_features=320, out_features=50, bias=True)
  (fc2): Linear(in_features=50, out_features=10, bias=True)
))
Traceback (most recent call last):
  File "D:\PyCharm\备份\Differential-Privacy-Based-Federated-Learning-master\main.py", line 147, in <module>
    w, loss = local.train(net=copy.deepcopy(net_glob).to(args.device))
  File "D:\PyCharm\备份\Differential-Privacy-Based-Federated-Learning-master\models\Update.py", line 57, in train
    log_probs = net(images)
  File "D:\Anaconda\envs\gym_gpu\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Anaconda\envs\gym_gpu\lib\site-packages\opacus\grad_sample\grad_sample_module.py", line 148, in forward
    return self._module(*args, **kwargs)
  File "D:\Anaconda\envs\gym_gpu\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\PyCharm\备份\Differential-Privacy-Based-Federated-Learning-master\models\Nets.py", line 38, in forward
    x = F.relu(F.max_pool2d(self.conv1(x), 2))
  File "D:\Anaconda\envs\gym_gpu\lib\site-packages\torch\nn\modules\module.py", line 1547, in _call_impl
    hook_result = hook(self, args, result)
  File "D:\Anaconda\envs\gym_gpu\lib\site-packages\opacus\grad_sample\grad_sample_module.py", line 288, in capture_activations_hook
    p._forward_counter += 1
AttributeError: 'Parameter' object has no attribute '_forward_counter'

**Comment by wenzhu23333** [comment]
请检查requirement.txt中的包版本是否满足

**Comment by zipckkk** [comment]
感谢，已解决，opacus包的版本问题
